---
plugins: ['prettier-plugin-svelte']
printWidth: 120
singleQuote: true
arrowParens: avoid
tabWidth: 4
overrides:
  - files: '*.svelte'
    options:
      tabWidth: 2
  - files: '*.yaml'
    options:
      tabWidth: 2
